### ISSUE TITLE
Unable to resolve module Dimensions

### ISSUE THREAD

**Issue by matt-d-rat** [lelandrichardson/react-native-segmented-view#9]
In `lib/SegmentedView.js` on line 11 there is a dependency declaration for a module called Dimensions:

``` javascript
var screen = require('Dimensions').get('window');
```

The dependency is not declared in the package.json of this project though, and I cannot find the npm package you are referring to anywhere in the registry (to manually install).

So currently this component is unusable in its current state.

**Comment by ColdJuzi** [comment]
// use ES6
import React, {PropTypes,} from 'react';
import {
    StyleSheet,
    Text,
    Image,
    View,
    TouchableHighlight,
    Dimensions,
} from 'react-native';

var screen = Dimensions.get('window');

**Comment by infacq** [comment]
is there any fix for this?
